#!/bin/bash
set -e

# 文本单模态消融训练入口（task1 -> task8，guidance_mode=text）。
# 仅使用文本引导进行 prompt 选择与对齐损失。
# 对应评测入口：sh scripts/ModalPrompt/Eval/eval_all_text_only.sh
#
# 全局参数（可在命令前覆盖）：
#   GPUS=0,1,2,3,4,5,6,7
#   DS_CONFIG=./scripts/zero2.json
#   MASTER_PORT=13200
#   SEED=42
#   NUM_WORKERS=16
#   SAVE_TOTAL_LIMIT=2
#   NNODES=2 NODE_RANK=0 MASTER_ADDR=10.0.0.1 NUM_GPUS_PER_NODE=8
GPUS=${GPUS:-0,1,2,3,4,5,6,7}
DS_CONFIG=${DS_CONFIG:-./scripts/zero2.json}
MASTER_PORT=${MASTER_PORT:-13200}
SEED=${SEED:-42}
NUM_WORKERS=${NUM_WORKERS:-16}
SAVE_TOTAL_LIMIT=${SAVE_TOTAL_LIMIT:-2}
NNODES=${NNODES:-1}
NODE_RANK=${NODE_RANK:-0}
MASTER_ADDR=${MASTER_ADDR:-127.0.0.1}
NUM_GPUS_PER_NODE=${NUM_GPUS_PER_NODE:-8}

GPUS="$GPUS" DS_CONFIG="$DS_CONFIG" MASTER_PORT="$MASTER_PORT" SEED="$SEED" NUM_WORKERS="$NUM_WORKERS" SAVE_TOTAL_LIMIT="$SAVE_TOTAL_LIMIT" NNODES="$NNODES" NODE_RANK="$NODE_RANK" MASTER_ADDR="$MASTER_ADDR" NUM_GPUS_PER_NODE="$NUM_GPUS_PER_NODE" sh ./scripts/ModalPrompt/Train/Ablation/TextOnly/1_Science.sh
GPUS="$GPUS" DS_CONFIG="$DS_CONFIG" MASTER_PORT="$MASTER_PORT" SEED="$SEED" NUM_WORKERS="$NUM_WORKERS" SAVE_TOTAL_LIMIT="$SAVE_TOTAL_LIMIT" NNODES="$NNODES" NODE_RANK="$NODE_RANK" MASTER_ADDR="$MASTER_ADDR" NUM_GPUS_PER_NODE="$NUM_GPUS_PER_NODE" sh ./scripts/ModalPrompt/Train/Ablation/TextOnly/2_TextVQA.sh
GPUS="$GPUS" DS_CONFIG="$DS_CONFIG" MASTER_PORT="$MASTER_PORT" SEED="$SEED" NUM_WORKERS="$NUM_WORKERS" SAVE_TOTAL_LIMIT="$SAVE_TOTAL_LIMIT" NNODES="$NNODES" NODE_RANK="$NODE_RANK" MASTER_ADDR="$MASTER_ADDR" NUM_GPUS_PER_NODE="$NUM_GPUS_PER_NODE" sh ./scripts/ModalPrompt/Train/Ablation/TextOnly/3_ImageNet.sh
GPUS="$GPUS" DS_CONFIG="$DS_CONFIG" MASTER_PORT="$MASTER_PORT" SEED="$SEED" NUM_WORKERS="$NUM_WORKERS" SAVE_TOTAL_LIMIT="$SAVE_TOTAL_LIMIT" NNODES="$NNODES" NODE_RANK="$NODE_RANK" MASTER_ADDR="$MASTER_ADDR" NUM_GPUS_PER_NODE="$NUM_GPUS_PER_NODE" sh ./scripts/ModalPrompt/Train/Ablation/TextOnly/4_GQA.sh
GPUS="$GPUS" DS_CONFIG="$DS_CONFIG" MASTER_PORT="$MASTER_PORT" SEED="$SEED" NUM_WORKERS="$NUM_WORKERS" SAVE_TOTAL_LIMIT="$SAVE_TOTAL_LIMIT" NNODES="$NNODES" NODE_RANK="$NODE_RANK" MASTER_ADDR="$MASTER_ADDR" NUM_GPUS_PER_NODE="$NUM_GPUS_PER_NODE" sh ./scripts/ModalPrompt/Train/Ablation/TextOnly/5_VizWiz.sh
GPUS="$GPUS" DS_CONFIG="$DS_CONFIG" MASTER_PORT="$MASTER_PORT" SEED="$SEED" NUM_WORKERS="$NUM_WORKERS" SAVE_TOTAL_LIMIT="$SAVE_TOTAL_LIMIT" NNODES="$NNODES" NODE_RANK="$NODE_RANK" MASTER_ADDR="$MASTER_ADDR" NUM_GPUS_PER_NODE="$NUM_GPUS_PER_NODE" sh ./scripts/ModalPrompt/Train/Ablation/TextOnly/6_Grounding.sh
GPUS="$GPUS" DS_CONFIG="$DS_CONFIG" MASTER_PORT="$MASTER_PORT" SEED="$SEED" NUM_WORKERS="$NUM_WORKERS" SAVE_TOTAL_LIMIT="$SAVE_TOTAL_LIMIT" NNODES="$NNODES" NODE_RANK="$NODE_RANK" MASTER_ADDR="$MASTER_ADDR" NUM_GPUS_PER_NODE="$NUM_GPUS_PER_NODE" sh ./scripts/ModalPrompt/Train/Ablation/TextOnly/7_vqav2.sh
GPUS="$GPUS" DS_CONFIG="$DS_CONFIG" MASTER_PORT="$MASTER_PORT" SEED="$SEED" NUM_WORKERS="$NUM_WORKERS" SAVE_TOTAL_LIMIT="$SAVE_TOTAL_LIMIT" NNODES="$NNODES" NODE_RANK="$NODE_RANK" MASTER_ADDR="$MASTER_ADDR" NUM_GPUS_PER_NODE="$NUM_GPUS_PER_NODE" sh ./scripts/ModalPrompt/Train/Ablation/TextOnly/8_OCRVQA.sh
